version: '3.8'

services:
  shortify-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://shortify-db:3306/shortify
      SPRING_DATASOURCE_USERNAME: shortify
      SPRING_DATASOURCE_PASSWORD: shortify
      SPRING_REDIS_HOST: shortify-redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - shortify-db
      - shortify-redis
    restart: unless-stopped

  shortify-db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shortify
      MYSQL_USER: shortify
      MYSQL_PASSWORD: shortify
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  shortify-redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped


volumes:
  db_data:
  redis_data: