spring:
  application:
    name: Shortify
  datasource:
    url: jdbc:mariadb://shortify-db:3306/shortify
    username: shortify
    password: shortify
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis

  data:
    redis:
      host: shortify-redis
      port: 6379