FROM node:22-alpine AS build

RUN apk update && apk add --no-cache git
WORKDIR /app

RUN git clone --branch master https://github.com/gulshan2052/ShortifyUI.git .

RUN npm install
RUN npm run build --prod

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/shortify-ui/browser /var/www/shortify

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
