FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /app

RUN git clone --branch master https://github.com/gulshan2052/Shortify.git .

RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
